name: Create Release

on:
  push:
    tags:
      - 'v*' # Will trigger on any tag that starts with v, like v1.0.0

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          
      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader
        
      - name: Create build directory
        run: mkdir -p build
        
      - name: Prepare plugin files
        run: |
          cp -r . build/rewardplugin
          cd build
          rm -rf rewardplugin/.git rewardplugin/.github rewardplugin/tests rewardplugin/phpunit.xml rewardplugin/phpunit.xml.dist rewardplugin/bin
          
      - name: Create ZIP file
        run: |
          cd build
          zip -r wc-reward-points.zip rewardplugin
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/wc-reward-points.zip
          name: WooCommerce Reward Points ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            # WooCommerce Reward Points ${{ github.ref_name }}
            
            A comprehensive reward points system for WooCommerce with account rewards, referrals, ambassador program, and Trustpilot review rewards.
            
            ## Features
            
            - Account Rewards: Points for account creation, purchases, and reviews
            - Social Sharing & Referral System: Generate referral links and reward points for successful referrals
            - Brand Ambassador Program: Apply, manage ambassadors, and track commissions
            - Trustpilot Review Rewards: Verify and reward customer reviews
            
            ## Installation
            
            1. Upload the zip file through WordPress admin panel
            2. Activate the plugin
            3. Configure settings through WooCommerce → Reward Points
            
            ## Requirements
            
            - WordPress 5.6+
            - WooCommerce 5.0+
            - PHP 7.2+ 